spring:
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/app_db

book:
  redis:
    enabled: true
  cache:
    cacheType: redis
    cache-names:
      - databaseEntities
    caches:
      databaseEntities:
        expiry: 10s
