spring:
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/app_db

book:
  redis:
    enabled: true
  cache:
    cacheType: redis
    cache-names:
      - entitiesFindAll
      - findByCategoryName
      - findByBookName
      - findByBookAuthor
      - entitySave
      - entityUpdate
    caches:
      entitiesFindAll:
        expiry: 10s
      findByCategoryName:
        expiry: 10s
      findByBookName:
        expiry: 10s
      findByBookAuthor:
        expiry: 10s
      entitySave:
        expiry: 10s
      entityUpdate:
        expiry: 10s